spring:
    #Configuraci贸n de MySQL
    datasource:
        url: jdbc:mysql://localhost:3306/fee_api_db?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
        username: root
        password: root
        driver-class-name: com.mysql.cj.jdbc.Driver
    #Configuraci贸n de Creaci贸n de Tablas (hibernate)
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    #Eliminamos el guardado de datos en cache de Thymeleaf
    thymeleaf:
        cache: false
    #Puerto de ejecuci贸n
    server:
        port: 8080
